
# To Know varable Data type
print(type(n))



DS[LKGL,L;VF,L;VFLMDKLMDL,MBLDNMLBN
   'MSLMVLDMKVLDMLKB
   'MV,LDMKLMDLKSM
MNVLNDLMMBVL,MDVF
MV DNVLMLM;DF VKDNKVNLD
MVLKSNLVMD;V,.D,FV'
   ,MVLKDNLV,/.D,V
VS LFMLKMSLML,SD;,,VDFK;VD .NJDSNLFM,S.NFKJDKLS FNBJFAHLM;NVIERHJMF.,MZLNKNKNLMDMDKJFK , VKMSDNKFZX BJADNF V A JFJM S, CNNFKMDLV DF HNFOJMLFMDL VDMVNDEINMNMD
   N VJDFNK;DMMLDF  B DJONMVJD D VKJDEOGVMLD VDF VOKMFML KEMOEFD
